# 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
# 特征矩阵
X = iris.data

# 结果标签的向量
y = iris.target

In [4]:
np.shape(X)

(150, 4)

In [5]:
np.shape(y)

(150,)

## train_test_split

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
# 生成一个序列（例如0~100），再把这个序列打乱
shuffle_indexes = np.random.permutation(np.shape(y)[0])

In [8]:
shuffle_indexes

array([ 50,  78,  69, 131,  10,  34,   6,   9,  36,  71,  82, 141, 137,
        79,  59,  93,  22,  91, 122,  75,  88,   3,  89,  86,  12,  61,
        14, 132, 119, 121, 129,  33, 103,  13,  37,  47, 139, 125,  73,
        53,   2,  42, 114,  29, 138, 112,  52, 101,  97,  19, 123, 128,
       144,  81,  11, 109,  26, 116,  44,  80,  64,  83, 124,  74,  39,
        31,  58, 145, 102, 120,  76,  63,  65, 135,   8,  55,  77,  60,
        35, 149,  57,  43,   0, 110, 127,  62, 142,  96, 106, 126,  51,
        40, 104, 118,  68,  27,  87,  45,  15, 113, 115,  49,  16, 136,
       117,  66,   5,  21,  67, 140,  54, 100,  99,  30,  18,  72, 148,
        92,  24,  23,  85,  32,  70, 107,  56, 108, 105,  17, 134,  94,
        95,  38,  48,   7,  46,  20, 146, 130,  28,  84,  90,   1, 111,
        25, 133, 143,  41, 147,   4,  98])

In [9]:
test_ratio = 0.2
test_size = int(np.shape(X)[0] * test_ratio)

In [10]:
test_size

30

In [11]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [12]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]


## 使用我们的算法

In [13]:
from c1_knn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y,seed=1)

### 先试试使用之前自己写的KNNClassifier

In [15]:
from  c1_knn.kNN import KNNClassifier

In [16]:
my_knn_clf = KNNClassifier(k=3)

In [17]:
my_knn_clf.fit(X_train, y_train)

kNN(k=3)

In [18]:
y_predict = my_knn_clf.predict(X_test)
y_predict

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 2, 1, 0, 0, 1, 2])

In [19]:
y_test

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 2, 1, 0, 0, 1, 2])

In [21]:
# 正确率
np.sum(y_predict==y_test) / len(y_test)

1.0

### sklearn中的train_test_split

In [22]:
from sklearn.model_selection._split import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [26]:
from sklearn.neighbors.classification import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(X_train, y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [27]:
y_predict = knn_clf.predict(X_test)
y_predict

array([1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0, 2,
       0, 1, 1, 0, 1, 2, 2])

In [30]:
# 准确率
np.sum(y_predict==y_test)/len(y_test)

1.0